spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

feeder:
  input:
    folder: input
  process:
    folder: processed
  report:
    folder: report  
  rate: 5000  